-- ---------------------------------------------------------------------------
-- CDG Claims Management — initial schema (PostgreSQL)
--
-- Generated from the JPA mapping, so `spring.jpa.hibernate.ddl-auto=validate`
-- (the setting used by the "postgres" profile) accepts it as-is. When an entity
-- changes, add a new V2__… migration rather than editing this file.
-- ---------------------------------------------------------------------------

-- Internal CDG users of the application.
CREATE TABLE app_users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(80)  NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    email         VARCHAR(150),
    role          VARCHAR(30)  NOT NULL
        CHECK (role IN ('QUALIFICATION', 'FO', 'MO', 'BO', 'VALIDATION', 'SUPERVISOR', 'ADMIN')),
    department    VARCHAR(100),
    active        BOOLEAN      NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    last_login_at TIMESTAMP(6) WITH TIME ZONE
);

-- Customer complaints. The routing state lives in Camunda; these columns are the
-- application's own projection of it, refreshed at every step and reconciled
-- periodically by WorkflowSyncService.
CREATE TABLE claims (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference             VARCHAR(30)  NOT NULL UNIQUE,

    customer_name         VARCHAR(150) NOT NULL,
    customer_email        VARCHAR(150),
    customer_phone        VARCHAR(40),
    customer_reference    VARCHAR(60),
    channel               VARCHAR(30)  NOT NULL
        CHECK (channel IN ('EMAIL', 'PHONE', 'BRANCH', 'WEB_PORTAL', 'POSTAL_MAIL', 'SOCIAL_MEDIA')),
    entity                VARCHAR(120),

    subject               VARCHAR(250)  NOT NULL,
    description           VARCHAR(4000) NOT NULL,
    type                  VARCHAR(40)   NOT NULL
        CHECK (type IN ('DEPOSIT_CONSIGNATION', 'PENSION_RETIREMENT', 'ACCOUNT_MANAGEMENT',
                        'PAYMENT_TRANSFER', 'FEES_CHARGES', 'DOCUMENT_REQUEST', 'DELAY',
                        'SERVICE_QUALITY', 'TECHNICAL_ISSUE', 'OTHER')),
    predicted_type        VARCHAR(40)
        CHECK (predicted_type IN ('DEPOSIT_CONSIGNATION', 'PENSION_RETIREMENT', 'ACCOUNT_MANAGEMENT',
                                  'PAYMENT_TRANSFER', 'FEES_CHARGES', 'DOCUMENT_REQUEST', 'DELAY',
                                  'SERVICE_QUALITY', 'TECHNICAL_ISSUE', 'OTHER')),
    prediction_confidence FLOAT(53),
    priority              VARCHAR(20) NOT NULL
        CHECK (priority IN ('LOW', 'NORMAL', 'HIGH', 'URGENT')),

    process_instance_key  BIGINT,
    process_version       INTEGER,
    status                VARCHAR(30) NOT NULL
        CHECK (status IN ('IN_QUALIFICATION', 'IN_FRONT_OFFICE', 'IN_MIDDLE_OFFICE',
                          'IN_BACK_OFFICE', 'IN_VALIDATION', 'REJECTED', 'RESOLVED', 'CANCELLED')),
    current_step          VARCHAR(30)
        CHECK (current_step IN ('QUALIFICATION', 'FRONT_OFFICE', 'MIDDLE_OFFICE',
                                'BACK_OFFICE', 'VALIDATION')),
    current_assignee      VARCHAR(80),
    step_started_at       TIMESTAMP(6) WITH TIME ZONE,
    sla_due_at            TIMESTAMP(6) WITH TIME ZONE,
    sla_breached          BOOLEAN NOT NULL,
    return_count          INTEGER NOT NULL,

    resolution            VARCHAR(4000),
    rejection_reason      VARCHAR(1000),

    created_by            VARCHAR(80),
    created_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    closed_at             TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX idx_claims_status ON claims (status);
CREATE INDEX idx_claims_process_instance ON claims (process_instance_key);
CREATE INDEX idx_claims_created_at ON claims (created_at);

-- Immutable audit trail, rendered as the timeline on the complaint page.
CREATE TABLE claim_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id      BIGINT      NOT NULL,
    type          VARCHAR(30) NOT NULL
        CHECK (type IN ('CREATED', 'PROCESS_STARTED', 'TASK_CREATED', 'TASK_ASSIGNED',
                        'TASK_UNASSIGNED', 'TASK_COMPLETED', 'ESCALATED', 'RETURNED', 'REJECTED',
                        'RESOLVED', 'CANCELLED', 'SLA_BREACHED', 'NOTIFIED', 'COMMENT')),
    step          VARCHAR(30)
        CHECK (step IN ('QUALIFICATION', 'FRONT_OFFICE', 'MIDDLE_OFFICE', 'BACK_OFFICE', 'VALIDATION')),
    decision      VARCHAR(20)
        CHECK (decision IN ('VALIDATE', 'REJECT', 'ANSWER', 'ESCALATE', 'APPROVE', 'RETURN')),
    actor         VARCHAR(80),
    actor_role    VARCHAR(30),
    comment       VARCHAR(2000),
    user_task_key BIGINT,
    occurred_at   TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_claim_events_claim ON claim_events (claim_id);

-- In-app notifications addressed to a single user.
CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient       VARCHAR(80)   NOT NULL,
    title           VARCHAR(200)  NOT NULL,
    message         VARCHAR(1000) NOT NULL,
    level           VARCHAR(20)   NOT NULL
        CHECK (level IN ('INFO', 'SUCCESS', 'WARNING', 'DANGER')),
    claim_id        BIGINT,
    claim_reference VARCHAR(30),
    read_flag       BOOLEAN       NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_notifications_recipient ON notifications (recipient, read_flag);

-- Per-year counter behind the REC-YYYY-NNNNNN references.
CREATE TABLE reference_counters (
    scope      VARCHAR(10) PRIMARY KEY,
    last_value BIGINT NOT NULL
);
